错误和异常
==========================================
##语法错误
例如，少了冒号（:）:
	>>> while True print('Hello world')
	  File "<stdin>", line 1, in ?
		while True print('Hello world')
					   ^
	SyntaxError: invalid syntax
	
##异常
运行时导致一个错误，执行时探测到的错误被成为 exception：

	>>> 10 * (1/0)
	Traceback (most recent call last):
	  File "<stdin>", line 1, in ?
	ZeroDivisionError: int division or modulo by zero
	>>> 4 + spam*3
	Traceback (most recent call last):
	  File "<stdin>", line 1, in ?
	NameError: name 'spam' is not defined
	>>> '2' + 2
	Traceback (most recent call last):
	  File "<stdin>", line 1, in ?
	TypeError: Can't convert 'int' object to str implicitly
	
##处理异常
一个 try 语句可以有多于一条的 except 语句, 用以指定不同的异常. 但至多只有一个会被执行：
** 首先, try clause (在 try 和 except 之间的语句) 将被执行；  
** 如果没有异常发生, except clause 将被跳过, try 语句就算执行完了；  
** 如果在 try 语句执行时, 出现了一个异常, 该语句的剩下部分将被跳过. 然后如果它的类型匹配到了 except 后面的异常名, 那么该异常的语句将被执行, 而执行完后会运行 try 后面的问题；  
** 如果一个异常发生时并没有匹配到 except 语句中的异常名, 那么它就被传到 try 语句外面; 如果没有处理, 那么它就是 unhandled exception 并且将会像前面那样给出一个消息然后执行。  

try ... except 语句可以有一个可选的 else 语句, 在这里, 必须要放在所有 except 语句后面. 它常用于没有产生异常时必须执行的语句 ；  

##抛出异常
raise 语句允许程序员强制一个特定的异常的发生：

	>>> try:
	...     raise NameError('HiThere')
	... except NameError:
	...     print('An exception flew by!')
	...     raise
	...
	An exception flew by!
	Traceback (most recent call last):
	  File "<stdin>", line 2, in ?
	NameError: HiThere

##自定义异常

	>>> class MyError(Exception):
	...     def __init__(self, value):
	...         self.value = value
	...     def __str__(self):
	...         return repr(self.value)
	...
	>>> try:
	...     raise MyError(2*2)
	... except MyError as e:
	...     print('My exception occurred, value:', e.value)
	...
	My exception occurred, value: 4
	>>> raise MyError('oops!')
	Traceback (most recent call last):
	  File "<stdin>", line 1, in ?
	__main__.MyError: 'oops!'
		
##定义清理动作
 finally 语句在任何情况下都被执行：  

	>>> def divide(x, y):
	...     try:
	...         result = x / y
	...     except ZeroDivisionError:
	...         print("division by zero!")
	...     else:
	...         print("result is", result)
	...     finally:
	...         print("executing finally clause")
	...
	>>> divide(2, 1)
	result is 2.0
	executing finally clause
	>>> divide(2, 0)
	division by zero!
	executing finally clause
	>>> divide("2", "1")
	executing finally clause
	Traceback (most recent call last):
	  File "<stdin>", line 1, in ?
	  File "<stdin>", line 3, in divide
	TypeError: unsupported operand type(s) for /: 'str' and 'str' 
	
##预定义的清理动作
with 语句就允许像文件这样的对象在使用后会被正常的清理掉：

	with open("myfile.txt") as f:
		for line in f:
			print(line)